name: Weekly PR from Development to Main

on:
    schedule:
        - cron: '0 1 * * 0' # Runs every Sunday at 1 AM UTC
    workflow_dispatch: # Allow manual triggering

jobs:
    create-pull-request:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Install GitHub CLI
            - name: Install GitHub CLI
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gh

            # Create or update the pull request
            - name: Create or update PR
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # Check if a PR already exists
                  if gh pr view --base main --head development --json number --jq '.number'; then
                    # Update the existing PR
                    gh pr edit $(gh pr view --base main --head development --json number --jq '.number') \
                      --title "Weekly Update: Development to Main" \
                      --body "This is an automated pull request."
                  else
                    # Create a new PR
                    gh pr create --base main --head development \
                      --title "Weekly Update: Development to Main" \
                      --body "This is an automated pull request."
                  fi
